Material theme: add icon support
dojo/themes pull request #62
Opened 2019-05-25 00:57 UTC by msssk

**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [ ] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [ ] Unit or Functional tests are included in the PR

**Description:**

* add `material-design-icons` to dev dependencies
* update `src/material/icon.m.css` to load Material Icons font and apply appropriate fonts to icon component CSS classes

Resolves #61

2019-05-25 01:08 UTC, msssk commented
If we update the structure of the `icon` component to insert the icon name as the content of the `<i>` element then we don't need all of the CSS classes in this theme.

2019-11-18 21:01 UTC, tomdye approved these changes

2019-11-18 21:02 UTC, tomdye requested changes
just thought, does this work built with the relative node_modules paths?

2019-12-10 17:25 UTC, tomdye commented
@msssk please re-raise this against widgets. Themes has been ported there.

2019-12-10 17:25 UTC, closed without merging